const GLASS = 'GLASS';
const SUNGLASS = 'SUNGLASS';
const LENSES = 'LENSES';
const GLASS_CLEANER = 'GLASS_CLEANER';
const LENS_CLEANER = 'LENS_CLEANER';

const PRODUCT_TYPES = {
    GLASS,
    SUNGLASS,
    LENSES,
    GLASS_CLEANER,
    LENS_CLEANER,
};

module.exports = {
    GLASS,
    SUNGLASS,
    LENSES,
    GLASS_CLEANER,
    LENS_CLEANER,

    PRODUCT_TYPES
}