const GLASS_TYPE = 'GLASS';
const SUNGLASS_TYPE = 'SUNGLASS';
const LENSES_TYPE = 'LENSES';
const GLASS_CLEANER_TYPE = 'GLASS_CLEANER';
const LENS_CLEANER_TYPE = 'LENS_CLEANER';

const PRODUCT_TYPES = [
    GLASS_TYPE,
    SUNGLASS_TYPE,
    LENSES_TYPE,
    GLASS_CLEANER_TYPE,
    LENS_CLEANER_TYPE,
];

module.exports = {
    GLASS_TYPE,
    SUNGLASS_TYPE,
    LENSES_TYPE,
    GLASS_CLEANER_TYPE,
    LENS_CLEANER_TYPE,

    PRODUCT_TYPES
}