const GLASS_TYPE = 'Glass';
const SUNGLASS_TYPE = 'Sunglass';
const LENSES_TYPE = 'Lenses';
const GLASS_CLEANER_TYPE = 'GlassCleaner';
const LENS_CLEANER_TYPE = 'LensCleaner';

const PRODUCT_TYPES = [
    GLASS_TYPE,
    SUNGLASS_TYPE,
    LENSES_TYPE,
    GLASS_CLEANER_TYPE,
    LENS_CLEANER_TYPE,
    CONTACT_LENSES_TYPE,
    OPTICAL_FRAME_TYPE
];

module.exports = {
    GLASS_TYPE,
    SUNGLASS_TYPE,
    LENSES_TYPE,
    GLASS_CLEANER_TYPE,
    LENS_CLEANER_TYPE,

    PRODUCT_TYPES
}